vich_uploader:
    db_driver: orm

    mappings:
       map_albums:
           uri_prefix: /plugs/photo/albums
           upload_destination: '%kernel.project_dir%/public/plugs/photo/albums'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
