vich_uploader:
    db_driver: orm

    mappings:
       map_albums:
           uri_prefix: '%app.path.display_albums%'
           upload_destination: '%kernel.project_dir%/public%app.path.map_albums%'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
           directory_namer: ~
           delete_on_remove: true
           inject_on_load: true
           delete_on_update: true

