vich_uploader:
    db_driver: orm

    mappings:
       map_albums:
           uri_prefix: '%app.path.map_albums%'
           upload_destination: '%kernel.project_dir%/public%app.path.map_albums%'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
